Video section responsive
front-end-by-rimantas/19-grupe-portfolio-mitech pull request #85
Opened 2020-12-13 13:58 UTC by martynas3113

Video section responsive design

2020-12-13 18:05 UTC, bemze approved these changes, later dismissed
LGTM

2020-12-13 18:52 UTC, pigma15 requested changes
![image](https://user-images.githubusercontent.com/45840501/102020902-db59b980-3d84-11eb-8ebf-b8b2cb294562.png)
Irasai easantys tarp komentaru aptvarko 'play' knopke.
Siaurejant eranui mazeja ir video konteinerio aukstis.

2020-12-14 10:44 UTC, martynas3113 commented
> Siaurejant ekranui turetu mazeti ir video konteinerio aukstis.
> 
> ![image](https://user-images.githubusercontent.com/45840501/102020902-db59b980-3d84-11eb-8ebf-b8b2cb294562.png)
> Irasai easantys tarp komentaru aptvarko 'play' knopke.

Inesti pakeitimai ir sutvarkytos iconos

2020-12-14 10:45 UTC, martynas3113 commented
> Siaurejant ekranui turetu mazeti ir video konteinerio aukstis.
> 
> ![image](https://user-images.githubusercontent.com/45840501/102020902-db59b980-3d84-11eb-8ebf-b8b2cb294562.png)
> Irasai easantys tarp komentaru aptvarko 'play' knopke.

Issiaiskinau su auksciu ir pastumdziau teksta, kad mobilioje versijoje atrodytu gerai

2020-12-14 13:23 UTC, pigma15 approved these changes
lgtm

2020-12-14 19:35 UTC, bemze approved these changes
LGTM

2020-12-14 19:35 UTC, merged