Button default
front-end-by-rimantas/19-grupe-portfolio-mitech pull request #86
Opened 2020-12-13 17:57 UTC by bemze

2020-12-13 22:19 UTC, pigma15 requested changes
Staciakampiai mygtukai graziai, bet services.css mygtukai su position:absolute truputi issitasko. Hero-section, variables.css ir button.css pakeitimus palikciau vietoj, bet our services.css ir su juo susijusius pokycius html'e reikia taisyt arba tam kartui isvis palikti, kaip buvo

2020-12-14 10:25 UTC, 2MariusG approved these changes, later dismissed
LGTM

2020-12-14 19:01 UTC, bemze commented
service btn fixed

2020-12-14 19:49 UTC, martynas3113 requested changes
Korteles su mygtukais atrodo gerai, bet reikia H6 ir H3 sutvarkyt.

2020-12-14 20:06 UTC, 2MariusG approved these changes
Bemze, Its good to me

2020-12-14 20:10 UTC, martynas3113 approved these changes
LGTM

2020-12-14 20:11 UTC, martynas3113 approved these changes

2020-12-14 20:18 UTC, pigma15 approved these changes
lgtm btn :)

2020-12-14 20:18 UTC, merged